Edit-Menu is added with three buttons and their working functions
cagdasgerede/JavaCheckers pull request #10
Opened 2020-12-12 18:39 UTC by omerfarukpolat

I have done my first commit on my issue (Making an edit menu which includes replace or remove a pawn from board and when the player is ready then let him/her resume game) . I added a pop-up menu, you can enable it with pressing "tab" key on your keyboard. First user have to select a pawn then;

- If he/she wants to remove it, then clickes "remove selected pawn" button. 
- If he/she wants to replace it, he/she selects 1 more field from board which is valid and empty, then clickes "Replace selected pawn" button.
- When user is ready, then clickes "ready" button to continue the game.

I don't like the colors of the menu  that I choose, maybe I could change its colors and design.
I didn't add the feature that if a pawn is replaced to the queen pawn region, then its automatically being a queen pawn. In this version, it is still stays as a normal pawn.

2020-12-12 20:54 UTC, omerfarukpolat commented
Hocam I also changed my menu and buttons design and actually I liked that version now.

2020-12-15 11:47 UTC, omerfarukpolat commented
Demo link: https://youtu.be/WFiFC3wmhEM

2020-12-15 13:47 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/Checkers.java
> +import javafx.scene.control.*;
* kullanma
Hangi class gerekiyorsa onu açık olarak yaz.

2020-12-15 13:47 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/Checkers.java
> +import javafx.scene.control.MenuBar;
Importların sıralaması yanlış.

2020-12-15 13:47 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/Design.java
> +
gereksiz newlinelar

2020-12-15 13:47 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/pawns/PawnClass.java
> +
gereksiz newline lar

2020-12-15 13:49 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +import javafx.application.Platform;
Bu class şişmeye başlamış. Buradaki değişikliklerini farklı classlara taşı.

2020-12-15 13:49 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +import javax.swing.*;
* kullanma

2020-12-15 13:55 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +    public boolean isEditMenuActive = false;
public yapma. Bunun yerine accessor metot yaz

2020-12-15 13:56 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +            }
fix indentation

2020-12-15 13:57 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +                    roundWithoutKick = 0;
Buradaki kod bloğunda çok fazla iç içe if else var. Buradaki kodu refactor et ve daha sade bir kod haline getir. Gerekirse yeni manalı metotlar yaz ve onları çağır.

Şu anki haliyle çok kocaman maintenance'ı problem olacak bir formatta.

2020-12-15 13:58 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +        }else{
fix spacing

`} else {`

2020-12-15 13:58 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +                isSelected = true;
isSelected çok genel bir isim

2020-12-15 13:58 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +            if(event.getCode().equals(KeyCode.R)){
fix indentation

2020-12-15 13:59 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +    private void replacePawn(Coordinates oldCoordinates, Coordinates newCoordinates){
missing newline before the method start

2020-12-15 13:59 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +
Yeni bir dosyaya taşı. İhtiyaç duyulan değerler için accessor metotları tanımla.

2020-12-15 14:00 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +            String exitButtonPNG = this.getClass().getClassLoader().getResource("button_ready.png").getFile();
Burada geçen tüm dosya isimlerini constantlar olarak tanımla.

2020-12-15 14:01 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +            String command = e.getActionCommand();
Bu kısmı başka bir class içerisinde implement et ve ActionEvent i o classın objesine delegate etç

Böylece pencerenin görsel implementasyonu ile kullanıcı inputlarına nasıl reaksiyon verdiğini ayırmış olursun: (bakınız separation of concerns)

2020-12-15 14:04 UTC, cagdasgerede requested changes
Kod içerisinde bıraktığım notlara göre kodunu güncelle.

Kod basei olabildiğince sade ve okunabilir tutmaya çalışıyoruz. Bu sebeple yaptığın değişiklikleri yeni classlarda encapsulate etmeyi unutma. Separation of concerns'e göre farklı amaçları olan kodları birbirinden ayır.

Son olarak PRda yeni eklediğin özellikler ile ilgili herhangi bir test yazmamışsın. Yeni eklediğin özelliklerin çalışıp çalışmadığını kontrol eden manalı testler ekle.

2020-12-21 13:46 UTC, omerfarukpolat commented
Hocam değişiklikleri yaptım, testleri de UI olmadıkları müddetçe yazdım.

2021-03-22 23:57 UTC, closed without merging