new additions for save/load functions
cagdasgerede/JavaCheckers pull request #11
Opened 2020-12-12 21:42 UTC by furkanorten

I create key event functions for save and load ability. When player is playing the game, player can press the key "S" for saving the current game state. If player presses the key "S", then a menu appears for selecting the save location. In the same way, if player presses the key "L", then another menu appears for selecting the load location.

2020-12-15 09:53 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +import java.util.Optional;
İmport sırası hatalı. Düzeltin.

2020-12-15 09:55 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +            Alert alert = new Alert(Alert.AlertType.NONE);
Bu kodları bir class içerisine al. Bir başka arkadaşın bir menu üzerine çalışıyor. İkinizin de PRları merge olduktan sonra , bu yeni özelliği o menüden de çağırman gerekecek. O yüzden buradaki save ve load kodlarını bir class içerisine encapsulate et. Böylece hem buradan hem de menülerden kolaylıkla çağırabilirsin.

2020-12-15 09:55 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +            ButtonType saveToHome = new ButtonType("Home Directory");
Buraya istediğimiz klasörü seçebilme özelliği ekle.

2020-12-15 09:58 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +                    save.write(white_count + "\n");
Buradaki kod bloğu ile aşağıdaki saveToHome içerisindeki kod birbirinin neredeyse aynısı. Kod tekrarı yerine ortak kullanılan bir metot yaz.

2020-12-15 10:00 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +                    for(int i = 0; i < whiteCoords.size(); i++) {
Buradaki 4 for döngüsündeki kodlar hemen hemen aynı. Ortak bir metota bu kodları refactor et ve uygun parametrelerle o metodu çağır.

2020-12-15 10:01 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +                    for(int i = 0; i < whiteCoords.size(); i++) {
Benzer kod tekrarları bu for döngülerde de bar. Yukarıdaki yazdığıma benzer bir yaklalımla kodları daha sade hale getir.

2020-12-15 10:01 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/board/Board.java
> +                    System.out.println("You loaded a game!");
Kodda sysout görmek istemiyorum.

2020-12-15 10:04 UTC, cagdasgerede requested changes
Birincisi, kodda bıraktığım notlara bak. Ona göre kodunu güncelle.

İkincisi autosave özelliği de ekle. Periyodik olarak aralıklarla oyun save edilsin. Load ekranında da manual save edilmiş oyunlarla beraber autosave edilmiş oyun veya oyunlar da görünsün.

Son olarak, şu ana kadar yaptığım değişiklikleri ve autosave özelliğini demo eden bir video linkini burada paylaş

2020-12-16 01:14 UTC, furkanorten commented
Merhaba Hocam,
Dediğiniz gibi SaveLoad adında yeni bir class oluşturup kendi kodlarımı oraya aktardım. Daha sonra istediğiniz gibi yeni methodlar oluşturarak tekrar eden for döngülerini ortadan kaldırdım ve kodun karmaşık olmasını engelledim. Ayrıca istediğiniz autosave özelliğini de ekledim. Koddaki değişiklikleri ve eklenen yeni özelliklerin nasıl çalıştığını demo videomda anlattım. 
Demo linki : https://youtu.be/dC_rF0YgVmY

2020-12-19 17:17 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +        if(loc.equals("home")) {
home ve local i enum olarak tanimla. 
saveFile metodu bir enum alsin. if else kiyaslamalarinda enumi kullan

2020-12-19 17:17 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            file = new File("JavaCheckersSavedGame.txt");
Bu Stringi constant olarak tanimla.

2020-12-19 17:17 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            file = new File("JavaCheckersAutosavedGame.txt");
Bu Stringi constant olarak tanimla.

2020-12-19 17:17 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +        for(int x = 0; x <= 7; x++) {
7yi constant olarak tanimla

2020-12-19 17:19 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            e.printStackTrace();
Bu tür exceptionları log dosyasına logla

2020-12-19 17:19 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +        alert.setContentText("Game will be saved as 'JavaCheckersSavedGame.txt' to selected directory(Your Home Directory or Game Directory)");
Bu Stringi constant olarak tanımla

2020-12-19 17:21 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +                PawnClass pawn = new PawnClass(Pawn.PAWN, PawnColor.WHITE);
if içerisindeki block 4 kez tekrar ediyor. Bunu bir metota al ve 4 kez o metodu çağır.

2020-12-19 17:21 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            file = new File(userHomeFolder, "JavaCheckersSavedGame.txt");
use constant

2020-12-19 17:21 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            String userHomeFolder = System.getProperty("user.home");
use constant

2020-12-19 17:21 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            file = new File("JavaCheckersSavedGame.txt");
use constant

2020-12-19 17:21 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            file = new File("JavaCheckersAutosavedGame.txt");
use constant

2020-12-19 17:25 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            int white_count = Integer.parseInt(load.readLine());
Burayi sadeleştir.

```
int parseCoords(BufferedReader reader, ArrayList<String> coords) {
  int count = Integer.parseInt(load.readLine());  
  for(int i = 0; i < count; i++)
    coords.add(load.readLine());
  return count;
}
```

```
parseCoords(load, whiteCoords);
parseCoords(load, blackCoords);
parseCoords(load, whiteQueenCoords);
parseCoords(load, blackQueenCoords);
```

2020-12-19 17:29 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            ArrayList<String> blackCoords = new ArrayList<String>();
Burayı sadeleştir:

```
ArrayList<String> blackCoords = new ArrayList<>(),
    whiteCoords = new ArrayList<>(),
    blackQueenCoords = new ArrayList<>(),
    whiteQueenCoords = new ArrayList<>();
```

2020-12-19 17:31 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            for(int x = 0; x <= 7; x++) {
use constant

2020-12-19 17:41 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            e.printStackTrace();
Bu tür exceptionları log dosyasına logla.

2020-12-19 17:41 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +}
missing newline

2020-12-19 17:41 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            loadFile("home");
use enum

2020-12-19 17:41 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            loadFile("local");
enum

2020-12-19 17:41 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            loadFile("auto");
enum

2020-12-19 17:42 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +        alert.setContentText("Game will be loaded from selected directory if you have saved before as 'JavaCheckedSavedGame.txt'.(Your Home Directory or Game Directory or Autosave)");
move String to a constant

2020-12-19 17:44 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +        ButtonType loadFromHome = new ButtonType("Home Directory");
use constant

2020-12-19 17:45 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +        ButtonType loadFromLocal = new ButtonType("Game Directory");
use constant

2020-12-19 17:48 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +import java.io.*;
```java.io.*``` * kullanma. Kullandiklarini acikca listele

2020-12-19 17:49 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +import pl.nogacz.checkers.board.*;
yildiz kullanma. Kullandiklarini acikca listele

2020-12-19 17:49 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +import pl.nogacz.checkers.pawns.*;
* kullanma. Kullandiklarini acikca listele

2020-12-19 17:51 UTC, cagdasgerede commented on src/main/java/pl/nogacz/checkers/application/SaveLoad.java
> +            for(int y = 0; y <= 7; y++) {
use constat

2020-12-19 17:57 UTC, cagdasgerede requested changes
Kodlarını bıraktığım notlara göre güncelle.

Eklediğin özellikler ile ilgili manalı unit testler yaz.

Review etmemi istediğinde bana assign etmeyi unutma.

2020-12-24 11:51 UTC, furkanorten commented
Merhaba Hocam,
Kodda istediğiniz değişiklikleri yaptım. Ayrıca test yazmamı istemiştiniz. Projede test klasörü olmadığı için kendim oluşturdum ve içinde test dosyamı yazdım. Testlerimin geçerli olabilmesi için build.gradle dosyasının dependencies kısmında değişiklikler yapmak durumunda kaldım.

2021-03-22 23:57 UTC, closed without merging